import random

from pymongo import MongoClient
from db.connection_credentials import mongodb_url


class QuestionsToUser:
    def __init__(self):
        client = MongoClient(mongodb_url)
        self.database = client['telegram_bot_data']

    def store_data(self, question: str, answer: str, explanation: str, difficulty: str, user_name: str, user_id: str):
        collection = self.database['Questions']

        db_question = collection.find_one({'question': question})

        if db_question:
            db_question['answers'][user_id] = answer
            db_question['explanations'][user_id] = explanation
            db_question['users_details'][user_id] = user_name

            collection.replace_one({'question': question}, db_question)

        else:
            data = {
                'question': question,
                'answers': {user_id: answer},
                'explanations': {user_id: explanation},
                'difficulty': difficulty,
                'users_details': {user_id: user_name}
            }

            collection.insert_one(data)

        return f"Question: '{question}'. {user_name} of id {user_id} answer: '{answer}'. Explanation: '{explanation}'"

    def generate_question(self):
        collection = self.database['GeneratedQuestions']

        questions = [
            'What is your name?',
            'How old are you?',
            'Where do you live?',
            'What is your favorite color?',
            'What do you do for a living?',
            'What are your hobbies?',
            'What is your favorite food?',
            'Do you have any pets?',
            'What is your favorite movie?',
            'What kind of music do you like?',
            'Do you like to travel?',
            'What is your dream job?',
            'What is your favorite book?',
            'Do you play any sports?',
            'What is your favorite season?',
            'Do you have any siblings?',
            'What is your favorite TV show?',
            'Do you prefer coffee or tea?',
            'What is your favorite holiday?',
            'What is your favorite dessert?',
            'Do you like cooking?',
            'What is your favorite animal?',
            'Do you have a favorite quote?',
            'What is your favorite app?',
            'Do you prefer the beach or the mountains?',
            'What is your favorite time of day?',
            'What is your favorite sport to watch?',
            'What is your favorite kind of weather?',
            'Do you like reading books or watching movies?',
            'What is your favorite superhero?',
            'Do you prefer Android or iOS?',
            'What is your favorite restaurant?',
            'What is your favorite childhood memory?',
            'Do you like to play video games?',
            'What is your favorite ice cream flavor?',
            'What is your favorite type of cuisine?',
            'Do you prefer sweet or savory snacks?',
            'What is your favorite board game?',
            'What is your favorite type of exercise?',
            'Do you like to draw or paint?',
            'What is your favorite flower?',
            'Do you prefer summer or winter?',
            'What is your favorite fruit?',
            'Do you like going to the gym?',
            'What is your favorite hobby to do indoors?',
            'What is your favorite hobby to do outdoors?',
            'Do you prefer sunrises or sunsets?',
            'What is your favorite kind of cake?',
            'Do you like gardening?',
            'What is your favorite place to visit?',
            'What is your favorite drink?',
            'Do you like fishing?',
            'What is your favorite subject in school?',
            'What is your favorite holiday tradition?',
            'Do you prefer books or e-books?',
            'What is your favorite kind of pie?',
            'Do you like hiking?',
            'What is your favorite way to relax?',
            'Do you like camping?',
            'What is your favorite snack?',
            'Do you like puzzles?',
            'What is your favorite video game?',
            'Do you prefer calling or texting?',
            'What is your favorite TV series?',
            'Do you like roller coasters?',
            'What is your favorite thing to do on a rainy day?',
            'Do you like to dance?',
            'What is your favorite candy?',
            'Do you prefer cats or dogs?',
            'What is your favorite way to spend a weekend?',
            'Do you like swimming?',
            'What is your favorite thing about your hometown?',
            'Do you like attending concerts?',
            'What is your favorite thing to do at the beach?',
            'Do you like to write?',
            'What is your favorite board game?',
            'Do you like to bake?',
            'What is your favorite holiday activity?',
            'Do you like going to museums?',
            'What is your favorite thing to do in the winter?',
            'Do you like ice skating?',
            'What is your favorite thing to do in the summer?',
            'Do you like playing cards?',
            'What is your favorite way to stay active?',
            'Do you like going to the zoo?',
            'What is your favorite memory from last year?',
            'Do you like going to the park?',
            'What is your favorite way to spend a day off?',
            'Do you like rollerblading?',
            'What is your favorite thing to do in the spring?',
            'Do you like going to the theater?',
            'What is your favorite type of sandwich?',
            'Do you like doing yoga?',
            'What is your favorite thing to do on a road trip?',
            'Do you like skiing or snowboarding?',
            'What is your favorite way to unwind?',
            'Do you like playing musical instruments?',
            'What is your favorite type of soup?',
            'Do you like watching sports?',
            'What is your favorite way to celebrate your birthday?',
            'Do you like doing arts and crafts?',
            'What is your favorite kind of pasta?',
            'Do you like stargazing?',
            'What is your favorite type of salad?',
            'Do you like participating in trivia games?',
            'What is your favorite way to spend time with family?',
            'Do you like going to amusement parks?',
            'What is your favorite kind of sandwich?',
            'Do you like going to the library?',
            'What is your favorite thing to do on a rainy day?',
            'Do you like solving riddles?',
            'What is your favorite way to spend a quiet evening?',
            'Do you like watching documentaries?',
            'What is your favorite kind of cookie?',
            'Do you like learning new languages?',
            'What is your favorite outdoor activity?',
            'Do you like taking long walks?',
            'What is your favorite thing to do on a sunny day?',
            'Do you like going to festivals?',
            'What is your favorite thing to cook?',
            'Do you like listening to podcasts?',
            'What is your favorite type of fish?',
            'Do you like exploring new cities?',
            'What is your favorite type of tree?',
            'Do you like going to the beach?',
            'What is your favorite breakfast food?',
            'Do you like going on bike rides?',
            'What is your favorite way to spend a holiday?',
            'Do you like playing board games?',
            'What is your favorite place to relax?',
            'Do you like trying new restaurants?',
            'What is your favorite drink to have in the morning?',
            'Do you like going to the gym?',
            'What is your favorite way to spend time with friends?',
            'Do you like having picnics?',
            'What is your favorite thing to do in the fall?',
            'Do you like attending workshops?',
            'What is your favorite kind of smoothie?',
            'Do you like walking in the rain?',
            'What is your favorite thing to do on a day off?',
            'Do you like volunteering?',
            'What is your favorite board game?',
            'Do you like going to the countryside?',
            'What is your favorite thing about summer?',
            'Do you like visiting historical sites?',
            'What is your favorite comfort food?',
            'Do you like watching reality TV shows?',
            'What is your favorite activity to do with your family?',
            'Do you like playing chess?',
            'What is your favorite thing about winter?',
            'Do you like going to the aquarium?',
            'What is your favorite type of pizza?',
            'Do you like doing crossword puzzles?',
            'What is your favorite way to stay healthy?',
            'Do you like visiting art galleries?',
            'What is your favorite type of burger?',
            'Do you like building things?',
            'What is your favorite thing about spring?',
            'Do you like learning about history?',
            'What is your favorite type of juice?',
            'Do you like going to carnivals?',
            'What is your favorite way to stay fit?',
            'Do you like cooking with friends?',
            'What is your favorite type of flower?',
            'Do you like watching comedies?',
            'What is your favorite thing to do on a Sunday?',
            'Do you like going to the farmer’s market?',
            'What is your favorite thing to bake?',
            'Do you like playing pool?',
            'What is your favorite holiday song?',
            'Do you like playing tennis?',
            'What is your favorite way to spend a Saturday?',
            'Do you like going to flea markets?',
            'What is your favorite way to get around the city?',
            'Do you like playing golf?',
            'What is your favorite thing to do with friends?',
            'Do you like taking pictures?',
            'What is your favorite way to stay cool in the summer?',
            'Do you like riding horses?',
            'What is your favorite way to enjoy the weekend?',
            'Do you like reading poetry?',
            'What is your favorite way to spend a rainy afternoon?',
            'Do you like going on road trips?',
            'What is your favorite holiday decoration?',
            'Do you like visiting botanical gardens?',
            'What is your favorite thing to do on a Friday night?',
            'Do you like playing trivia games?',
            'What is your favorite way to celebrate New Year’s Eve?',
            'Do you like birdwatching?',
            'What is your favorite way to spend a holiday weekend?',
            'Do you like playing with pets?',
            'What is your favorite dessert to make?',
            'Do you like going to the mountains?',
            'What is your favorite way to spend time outdoors?'
        ]
        question = random.choice(questions)
        db_question = collection.find_one({'question': question})

        while db_question:
            question = random.choice(questions)
            db_question = collection.find_one({'question': question})

        collection.insert_one({'question': question})
        return question
